---
- name: hosts
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - hosts

- name: database
  hosts: databases
  gather_facts: no
  become: true
  roles:
    - database

- name: webserver
  hosts: webservers
  gather_facts: no
  become: yes
  roles:
    - webserver

- name: proxy
  hosts: proxies
  gather_facts: no
  become: yes
  roles:
    - loadbalancer
