---
# tasks file for loadbalancer
- name: install packages
  package: name={{item}} state=installed
  with_items:
       - nginx
       - libsemanage-python
       - python-passlib

- name: selinux open http
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: copy proxy config
  template:
   src: proxy.j2
   dest: /etc/nginx/conf.d/proxy.conf
   backup: yes
  notify:
  - restart nginx

- name: copy nginx.conf
  copy:
   src: nginx.conf
   dest: /etc/nginx/nginx.conf
   force: yes
   mode: 0644
   backup: yes
   validate: nginx -t -c %s
  notify:
  - restart nginx

- name: copy htpasswd
  htpasswd:
   path: /etc/nginx/.htpasswd
   name: zippy
   password: "{{ proxy_password }}"
   mode: 0644
  notify:
  - restart nginx

- name: ensure nginx running
  service:
    name: nginx
    state: started

- name: ensure nginx running
  uri:
   url: "http://{{ ansible_host }}/"
   follow_redirects: all
   register: webpage
   timeout: 30
   user: zippy
   password: "{{ proxy_password }}"

- debug:
    msg: "Proxy is available under http://{{ ansible_host }}/"
