---
# tasks file for database
- name: install dependencies
  package: name={{item}} state=installed
  with_items:
       - mongodb
  environment:
    PATH: "{{ lookup('env', 'PATH') }}"

- name: prepare mongodb config file
  template:
   src: mongodb.conf.j2
   dest: /etc/mongodb.conf
   backup: yes
  notify:
  - restart mongodb

- meta: flush_handlers

- name: ensure mongodb running
  service:
    state: started
    name: mongodb

- name: ensure port is open
  wait_for:
    host: 0.0.0.0
    port: 27017
    delay: 10
    state: started
